### ISSUE TITLE
Archive broken on OSX Mountain Lion

### ISSUE THREAD

**Issue by cielavenir** [mackyle/xar#1]
I'm developing a Chrome/Safari extension.
https://code.google.com/p/ctouch/source/browse/

Please check Makefile and support/safari.rb.
This script works on Debian Linux, but fails on OSX Mountain Lion.
It seems archive was created, but when xar -xf,
Error while extracting archive:(ctouch.safariextension/ctouch_bootstrap.js): Error decompressing file (Undefined error: 0)

For your sake, otool -L is:
    /opt/local/lib/liblzma.5.dylib (compatibility version 6.0.0, current version 6.4.0)
    /opt/local/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.6)
    /opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.7)
    /opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /opt/local/lib/libxml2.2.dylib (compatibility version 11.0.0, current version 11.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
    /opt/local/lib/libiconv.2.dylib (compatibility version 8.0.0, current version 8.1.0)

**Comment by mackyle** [comment]
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by cielavenir** [comment]
mackyle, I don't know anything other than
Error while extracting archive:(ctouch.safariextension/ctouch_bootstrap.js): Error decompressing file (Undefined error: 0)

From this message what can I do?
~/bin/xar -cf ctouch.safariextz
is ok.
~/bin/xar --sign -f "ctouch.safariextz" --digestinfo-to-sign sha1.dat --sig-size 256 --cert-loc pem/ctouch_safari.der --cert-loc certs/appleca --cert-loc certs/rootca
corrupts the archive content.

**Comment by cielavenir** [comment]
Very sorry, adding --distribution switch worked.
https://code.google.com/p/xar/issues/detail?id=76#c20
I should have read original thread...

Now xar -xf ctouch.safariextz doesn't complain and Safari is also fine.
This thread can be closed now...
