### ISSUE TITLE
unable to compile on yosemite

### ISSUE THREAD

**Issue by stephenmathieson** [mackyle/xar#2]
after running `autogen.sh` and `configure`, `make` fails with:

```
gcc -Wall -g -O2  -fPIC -DPIC -dynamic -Iinclude -Iinclude -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -c lib/lzmaxar.c -o lib/lzmaxar.o
lib/lzmaxar.c:49:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^
1 error generated.
make: *** [lib/lzmaxar.o] Error 1
```

machine info:

```
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D2134
```

**Comment by mackyle** [comment]
On Aug 3, 2015, at 12:32, Stephen Mathieson wrote:

> after running autogen.sh and configure, make fails with:
> 
> gcc -Wall -g -O2  -fPIC -DPIC -dynamic -Iinclude -Iinclude -I/ 
> Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/ 
> Developer/SDKs/MacOSX10.10.sdk/usr/include/libxml2 -c lib/lzmaxar.c - 
> o lib/lzmaxar.o
> lib/lzmaxar.c:49:10: fatal error: 'lzma.h' file not found
> #include <lzma.h>
>          ^
> 1 error generated.
> make: **\* [lib/lzmaxar.o] Error 1

Apparently your configure environment differs from your build  
environment allowing configure to find the header but not make.

You can explicitly disable lzma by re-running configure like so:

./configure --without-lzma

**Comment by stephenmathieson** [comment]
perfect!  thanks!
