### ISSUE TITLE
Segmentation fault: core dumped

### ISSUE THREAD

**Issue by Anacondo** [mackyle/xar#9]
I think I found a pretty weird error with XAR while doing a whole system backup. I get a "Segmentation fault: core dumped" error after a while that I can't reproduce with TAR and seems to be isolated to one particular folder in my system.

Right now I can reproduce it by running XAR on this location:

> /home/steam/Steam/steamapps/common/Counter-Strike Source Dedicated Server/cstrike/maps

I'm using the command:

> xar -cvalf "[backup_location]/backup.xar.xz" "/home/steam/Steam/steamapps/common/Counter-Strike Source Dedicated Server/cstrike/maps"

It always crashes when it reaches the same file. However, if I XAR that file directly it does work with no problems. The file itself looks ok and can be opened with no problems. Here's a sample output:

> $ xar -cvalf /mnt/ext_hdd1/backups/backup_test.xar.xz *
> aim_deagle7k.bsp
> aim_deagle7k.nav
> awp_india_v2.bsp
> awp_india_v2.nav
> cs_747_css.bsp
> Segmentation fault (core dumped)

The crash doesn't seem to be related to compression. I tried lzma, gzip and no compression and it always crashes when I try to XAR the contents of that folder. The file system is ext4 and fsck shows no errors whatsoever.

This is dmesg's output after running the above XAR command:

> [Sun Apr 17 14:23:15 2016] xar[19243]: segfault at 0 ip 00007fabb1498e22 sp 00007ffde83bcfb0 error 6 in libxar.so.1[7fabb1486000+17000]

This is the output of the "uname -srvmp" command:

> Linux 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64

Output of the "xar -v --version" command:

> xar 1.6.1
> xar library version 0x01060180

**Comment by mackyle** [comment]
On Apr 20, 2016, at 09:35, Anacondo wrote:

> This is my first bug report, so please let me know if there's  
> anything further I should add.

Also, could you please run "uname -srvmp" and paste everything it  
outputs into your bug report.  Thanks.

**Comment by Anacondo** [comment]
Sure thing, i just added it at the end. Thank you.

**Comment by mackyle** [comment]
On Apr 21, 2016, at 15:11, Anacondo wrote:

> Sure thing, i just added it at the end. Thank you.
> 
> Hmmm.  GitHub seems to have eaten this response, so trying again, the  
> "uname" request was the second part of the response (thank you for  
> adding that output) and apparently it obliterated the first part.

Please run "xar -v --version" and paste everything it outputs into  
your bug report.  Thanks.

**Comment by Anacondo** [comment]
Added the output for "xar -v --version" to the report. This is weird, it seems GitHub is chopping the last part of your response here as well. No problem since I saw it on your email, though. Cheers.

**Comment by Anacondo** [comment]
any news on this?

**Comment by mackyle** [comment]
On May 19, 2016, at 06:35, Anacondo wrote:

> any news on this?

You never replied to my request for the output of:

xar -v --version

So I assumed you had dealt with the issue.

**Comment by Anacondo** [comment]
> You never replied to my request for the output of:

There is something seriously wrong with Github! My reply is right there in comment no. 5, and the output was added to the initial report. I will paste it here again, however:

Output of the "xar -v --version" command:

```
xar 1.6.1
xar library version 0x01060180
```

Hope you're getting this.

**Comment by Anacondo** [comment]
Did you get my last message?

**Comment by Anacondo** [comment]
Closing because of lack of interest
